// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebWarriors.Aquanetix.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace WebWarriors.Aquanetix.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615213701_AddDeviceIdToAlerts")]
    partial class AddDeviceIdToAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Dashboard.Domain.Model.Aggregates.QualityAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AnomalyStatus")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("anomaly_status");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DetectedParameters")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("detected_parameters");

                    b.Property<bool>("HasContaminationPeakPrediction")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_contamination_peak_prediction");

                    b.Property<int>("SensorSourceId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_source_id");

                    b.Property<double>("SeverityScore")
                        .HasColumnType("double")
                        .HasColumnName("severity_score");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("quality_analyses", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Monitoring.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_name");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<double>("Threshold")
                        .HasColumnType("double")
                        .HasColumnName("threshold");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
